"""inicial

Revision ID: 48f6c8248fb7
Revises: 
Create Date: 2026-05-29 14:15:00.344136

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f6c8248fb7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bloqueos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('config',
    sa.Column('clave', sa.Text(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.SmallInteger(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_procesados',
    sa.Column('wa_message_id', sa.Text(), nullable=False),
    sa.Column('procesado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('wa_message_id')
    )
    op.create_table('servicios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('buffer_min', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('gcal_event_id', sa.Text(), nullable=True),
    sa.Column('recordatorio', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.create_index('idx_citas_inicio', ['inicio'], unique=False)

    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.create_index('idx_mensajes_cliente', ['cliente_id', 'creado_en'], unique=False)

    # ### end Alembic commands ###

    # Anti-solape de citas activas (solo PostgreSQL): requiere btree_gist.
    # En SQLite el solapamiento se valida en la capa de aplicacion (services/agenda.py).
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
        op.execute(
            "ALTER TABLE citas ADD CONSTRAINT no_solape "
            "EXCLUDE USING gist (tstzrange(inicio, fin) WITH &&) "
            "WHERE (estado <> 'cancelada')"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TABLE citas DROP CONSTRAINT IF EXISTS no_solape")

    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.drop_index('idx_mensajes_cliente')

    op.drop_table('mensajes')
    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.drop_index('idx_citas_inicio')

    op.drop_table('citas')
    op.drop_table('usuarios_admin')
    op.drop_table('servicios')
    op.drop_table('mensajes_procesados')
    op.drop_table('horarios')
    op.drop_table('config')
    op.drop_table('clientes')
    op.drop_table('bloqueos')
    # ### end Alembic commands ###
